### ISSUE TITLE
Motion events not sent to MQTT for AD110

### ISSUE THREAD

**Issue by rakeshdas1** [dchesterton/amcrest2mqtt#16]
I have 2 AD110 doorbells that work great. They detect motion events via BlueIris and record perfectly. But for some reason, the motion event isn't sent to MQTT and I don't even have a "motion" topic in my MQTT broker:
![image](https://user-images.githubusercontent.com/6901641/120075314-5f1f0e00-c066-11eb-8932-376b62c07cd3.png)

I did see that when there is a motion trigger event, the "event" topic displays the following (in this order): 

    {"Code": "VideoMotion", "action": "Start"}
    {"Code": "AlarmLocal", "action": "Start"}
    {"Code": "AlarmLocal", "action": "Stop"}
    {"Code": "VideoMotion", "action": "Stop"}

As far as I can tell, we can just keep an eye out for the `VideoMotion` key and use that to signal any motion. I think this line in the python script directly contradicts that theory, hence not sending the motion signal to the MQTT server: `if (is_ad110 and code == "ProfileAlarmTransmit") or (code == "VideoMotion" and not is_ad110):`.  I think we should check for both the keys `ProfileAlarmTransmit` OR `VideoMotion` and then send the "motion" signal to the MQTT server in order to solve issue #13 as well . Although I don't understand why the devices send different payloads when motion is detected, maybe my doorbell is setup in a different configuration?

**Comment by dchesterton** [comment]
So the AD110 has some weird behaviour compared to the other devices. It sends a `VideoMoion` event for any motion and a `ProfileAlarmTransmit` for motion inside your configured zones. Therefore we listen for the `ProfileAlarmTransit` event as that's what you'd generally expect to be considered 'motion'  Do you have motion zones set up in the app?

By the way all events are posted to the `amcrest2mqtt/X/event` topic so you can use that potentially if you need custom behaviour.

**Comment by rakeshdas1** [comment]
Oh, that is very interesting. No, I do not have specific motion zones setup in the app, I just use the entire frame as one motion zone.

I will have to take a look at that topic and potentially create a custom sensor in Home Assistant to mitigate this.

Thanks for the guidance!
