### ISSUE TITLE
400 Client Error: Bad Request

### ISSUE THREAD

**Issue by leonardomrc** [dchesterton/amcrest2mqtt#17]
I deployed in Portainer and that's what I get from the logs:

```
29/05/2021 23:53:11 [INFO] Fetching storage sensors...

<Name:SERIAL> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://AmcrestIP:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Name:SERIAL> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://AmcrestIP:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Name:SERIAL> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://AmcrestIP6:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

29/05/2021 23:53:12 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://AmcrestIP:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo
```

I don't know how to fix this. If I type "http://AmcrestIP:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo" on an Internet browser, it asks me for username and password (admin:MYPASSWORD). Then, it shows:

```
Error
Bad Request!
```

**Comment by dchesterton** [comment]
Which Amcrest device are you using?

**Comment by leonardomrc** [comment]
AD110.

Important info: Although I can see the message above in the logs, Home Assistant seems to be able to get the correct status from the doorbell's entities such as "button press" etc.

**Comment by dchesterton** [comment]
Do you have an SD card installed? I think you might get that error if you don't.
