### ISSUE TITLE
[BUG] Fatal Python error: init_interp_main: can't initialize time

### ISSUE THREAD

**Issue by maxirus** [dchesterton/amcrest2mqtt#20]
When running on a Raspberry Pi 4, I get the following error:
```bash
Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6f40390 (most recent call first):
<no Python frame>
```

Based on other project threads (ie. [here](https://github.com/xirixiz/dsmr-reader-docker/issues/203#issuecomment-817354261)), it appears to be a problem with Alpine and the RPi.

Installing `libseccomp2` from backports is a workaround.

**Comment by maxirus** [comment]
Changing the base image from `alpine` to `slim-buster` resolves the issue.

**Comment by dchesterton** [comment]
I'd prefer to use `alpine` base images rather than `slim` to keep image sizes as small as possible and as it appears to be an issue just with Docker and Raspberry Pi 4's and there are documented fixes (e.g. https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/) I'm going to close this.

**Comment by maxirus** [comment]
@dchesterton we're talking about a difference of ~50mb between alpine and slim. You'll find more issues with Alpine down the road (ie. musl DNS) that just create more headaches than it's worth to save a few MBs for an image that will not be pulled too often. Image size is really only paramount in situations where you have highly elastic workloads.

I would strongly encourage you to reconsider as Debian based images have much better support, especially in the @Home environment. Or at the very least, build for both using a separate tag.

**Comment by dchesterton** [comment]
I've built many, many Docker images based on Alpine and it's always worked flawlessly. I'll happily use a more feature packed base image when I have a more complicated project with more dependencies but this is a fairly simple script and Alpine suits it just fine. I also disagree that image size doesn't matter much beyond Kubernetes etc. but that's a discussion for another day 🙂

There's a documented fix and this issue itself is not even a problem with Alpine per-se but more outdated dependencies on the host. Therefore, all things considered, I'm not going to add a Debian build and unnecessarily increase the complexity of the build process.
