### ISSUE TITLE
Polling Events?

### ISSUE THREAD

**Issue by BostonMikeGetHub** [dchesterton/amcrest2mqtt#28]
Thank you for your work.  I would love to use Amcrest2MQTT to automate turning on an outside light when someone presses the AD401 doorbell button after dark.  However it looks like you are polling data with a default of 1 hour interval. Is this true even for events such as the doorbell button being pressed?  If so, is it practical for Amcrest2MQTT to send a MQTT event when event occurs?  Is shorting this interval to a few seconds practical?  Thank you again.

**Comment by BostonMikeGetHub** [comment]
Opps, it looks like the polling is only for getting the amount of storage used.  Events are triggered as they happen, right? I have installed things like mqtt on my Synology NAS using Portainer but I had to follow step by step instruction videos.  Does anyone have a video or step by step instructions to install amcrest2mqtt?

**Comment by dchesterton** [comment]
Yeah, the polling only applies to fetching storage data. All events should happen immediately and I have automations based on my AD110 doorbell working well 🙂

I'm not too familiar with Portainer but it should be a case of adding a Docker container in the same way you have for your other containers and then setting the correct environment variables as per the README.
