### ISSUE TITLE
404 for getDeviceAllInfo on container launch

### ISSUE THREAD

**Issue by atonyshepherd** [dchesterton/amcrest2mqtt#3]
I've got the AD110, and when I launch the container, I get a 404 error trying to access `cgi-bin/storageDevice.cgi?action=getDeviceAllInfo` which I can confirm returns the same through a browser window. My device is presumably running the latest firmware, and I can run other commands against the API, just not this. Any ideas?

**Comment by dchesterton** [comment]
Do you have an SD card in your device and configured? I wonder if that URL returns a 404 if you don't have one?

**Comment by atonyshepherd** [comment]
I don't. That's weird that it'd give a 404 for that though. I'll see if
I've got an sd card I can put in it and see if that's the issue. I've got a
DVR streaming the rtsp feed, so I don't normally need the sd card.

**Comment by dchesterton** [comment]
Yeah it's a bit odd if that is the reason but it's the only thing I can think of. I've pushed an update which should handle the 404 and not crash the container at least.
