### ISSUE TITLE
Request: Need an online / offline state sensor

### ISSUE THREAD

**Issue by bagobones** [dchesterton/amcrest2mqtt#30]
If amcrest2mqtt loses contact with the doobell due to failed requests there is currently no way in HomeAssistant to know this as the MQTT sensor states just stay at their last value. 

Adding an offline / online sensor for when amcrest2mqtt is listening for events would be helpful.

**Comment by bagobones** [comment]
Next time it happens I will try and gather the logs as amcrest2mqtt also does not seem to recover after the door bell has been rebooted and other cases requiring a complete restart of amcrest2mqtt.

**Comment by dchesterton** [comment]
There is already an online/offline status but there was a bug where it doesn't recover properly if the doorbell is reset. I've added a fix to periodically ping the camera and restart the app if it cannot reach it. It should fix your issue 😄
