### ISSUE TITLE
BUG: gets stuck in a HTTPErrror loop if the camera is unavailable for a short time due to settings updates or reboot

### ISSUE THREAD

**Issue by bagobones** [dchesterton/amcrest2mqtt#32]
If I touch my camera via Surveillance station, the mobile app or reboot the camera, amcrest2mqtt will get stuck in an error loop that it does not recover from until the docker is completely restarted.

`
04/08/2021 11:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

04/08/2021 11:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

04/08/2021 12:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

04/08/2021 12:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

04/08/2021 13:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

04/08/2021 13:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

04/08/2021 14:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

04/08/2021 14:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

04/08/2021 15:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

04/08/2021 15:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

04/08/2021 16:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

04/08/2021 16:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

04/08/2021 17:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

04/08/2021 17:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

04/08/2021 18:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

04/08/2021 18:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

04/08/2021 19:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

04/08/2021 19:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

04/08/2021 20:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

04/08/2021 20:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

04/08/2021 21:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

04/08/2021 21:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

04/08/2021 22:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

04/08/2021 22:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

04/08/2021 23:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

04/08/2021 23:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

05/08/2021 00:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

05/08/2021 00:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

05/08/2021 01:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

05/08/2021 01:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

05/08/2021 02:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

05/08/2021 02:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

05/08/2021 03:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

05/08/2021 03:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

05/08/2021 04:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

05/08/2021 04:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

05/08/2021 05:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

05/08/2021 05:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

05/08/2021 06:33:08 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

05/08/2021 06:33:10 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo`

After a quick reboot, no issue re-connecting

`
05/08/2021 06:49:12 [INFO] App Version: 1.0.8

05/08/2021 06:49:12 [INFO] Fetching camera details...

05/08/2021 06:49:16 [INFO] Device type: AD110

05/08/2021 06:49:16 [INFO] Serial number: XXXXXXXXXXXXX

05/08/2021 06:49:16 [INFO] Software version: build:2020-09-22

05/08/2021 06:49:16 [INFO] Device name: Front Door

05/08/2021 06:49:16 [INFO] Writing Home Assistant discovery config...

05/08/2021 06:49:16 [INFO] Fetching storage sensors...

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

<Front Door:Z05B682CDBB89> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')

05/08/2021 06:49:17 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.103.8:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo

05/08/2021 06:49:17 [INFO] Listening for events...

05/08/2021 06:49:19 [INFO] {'Code': 'TimeChange', 'action': 'Pulse', 'index': '0', 'data': {'BeforeModifyTime': '2021-08-04 10:49:19', 'ModifiedTime': '2021-08-04 10:49:18'}}

05/08/2021 06:49:19 [INFO] {'Code': 'NTPAdjustTime', 'action': 'Pulse', 'index': '0', 'data': {'Address': '192.168.102.11', 'Before': '2021-08-04 10:49:17', 'result': 'true'}}

05/08/2021 06:50:43 [INFO] {'Code': 'VideoMotion', 'action': 'Start'}

05/08/2021 06:50:53 [INFO] {'Code': 'VideoMotion', 'action': 'Stop'}`

Suggested fix.. Back off after X failed tries pause and rest the connection

Suggested fix2 auto reboot the docker if X failed attempts in a row.

Due to this issue I have missed doorbell events several times as the mqtt state does not change when this is happening, it just shows available in homeassistant.. I have to manually check up on this docker from time to time and restart it.

**Comment by dchesterton** [comment]
I've added a fix to periodically ping the camera and restart the app if it cannot reach it. It should fix your issue 😄
