### ISSUE TITLE
Request:  MQTT message to send an audio clip to the camera speaker

### ISSUE THREAD

**Issue by rodpayne** [dchesterton/amcrest2mqtt#34]
Have you considered listening for an MQTT message that would send an audio clip to the camera speaker?

**Comment by conorlap** [comment]
Someone got 2-way audio and sending audio clip via the Tinycam app, all locally: https://www.reddit.com/r/BlueIris/comments/lpkt8z/achieved_local_doorbell_with_2_way_audio/

**Comment by dchesterton** [comment]
I'd happily accept PR(s) to add such functionality but truthfully I don't have the need myself, nor the time to implement such features unfortunately.
