### ISSUE TITLE
Container shutting down on connection loss.

### ISSUE THREAD

**Issue by Emotive9** [dchesterton/amcrest2mqtt#44]
It seems every time a ping reply is missed to the doorbell (AD410) the container shuts down. This also happens when my MQTT container is restarted. Is there a way for the app to just retry the connections (ping, MQTT login) instead of shutting down?

08/10/2021 15:14:15 [ERROR] Ping unsuccessful
08/10/2021 15:14:15 [INFO] Exiting app...

07/10/2021 15:52:48 [ERROR] Unexpected MQTT disconnection
07/10/2021 15:52:48 [INFO] Exiting app...

**Comment by rosiaantje** [comment]
Looks like : #43 is covering this?

**Comment by dchesterton** [comment]
The underlying library has been updated so I've removed the ping functionality as it's no longer needed. The app should now restart less.

Functionally, if you have the Docker container set to restart on exit there's no real world difference between re-connecting and restarting the container and it keeps the code a lot simpler so I won't be changing the way this works.
