### ISSUE TITLE
Unsupported version in HA. Can you update the image?

### ISSUE THREAD

**Issue by terslowe** [dchesterton/amcrest2mqtt#48]
WARNING (MainThread) [supervisor.resolution.evaluations.base] Found images: {'dchesterton/amcrest2mqtt'} which are not supported, remove these from the host! (more-info: https://www.home-assistant.io/more-info/unsupported/software)

**Comment by iceman73** [comment]
its due to it not being installed as an addon store item, but as a stand alone docker image

**Comment by terslowe** [comment]
How can i install it as addon store?

> its due to it not being installed as an addon store item, but as a stand alone docker image

**Comment by robsonke** [comment]
You can use my wrapper addon for the time being: https://github.com/robsonke/hassio-addons
