### ISSUE TITLE
Amcrest doorbell AD110  button status always on

### ISSUE THREAD

**Issue by dinki** [dchesterton/amcrest2mqtt#68]
Forgive me if I am misunderstanding, but my new Amcrest doorbell AD110  is always showing the binary_sensor.doorbell as on.  I was hoping that this device would toggle from off to on when the button is pressed but that's not what I'm experiencing.  Here's what I see when the button is pressed (and also a bit of motion from my hand):

```
Message 4 received on amcrest2mqtt/XXXXXXXXXXXXXXXXXXXX/doorbell at 7:10 PM:
on
QoS: 0 - Retain: false

Message 5 received on amcrest2mqtt/XXXXXXXXXXXXXXXXXXXX/event at 7:10 PM:
{
    "Code": "_DoTalkAction_",
    "action": "Pulse",
    "index": "0",
    "data": {
        "Action": "Invite",
        "CallID": "XXXXXXXXXXXXXXXXXXXX@XXXXXXXXXXXXXXXXXXXX@192.168.0.107",
        "CallSrcMask": 4
    }
}
QoS: 0 - Retain: false

Message 6 received on amcrest2mqtt/XXXXXXXXXXXXXXXXXXXX/event at 7:11 PM:
{
    "Code": "CallNoAnswered",
    "action": "Start",
    "index": "0",
    "data": {
        "CallID": "1"
    }
}
QoS: 0 - Retain: false
```

Any help fixing/understanding this better is greatly appreciated.  Thanks!

**Comment by dinki** [comment]
No longer a problem .  Sorry for the bother.

**Comment by carlos-sarmiento** [comment]
@dinki I'm having the same issue. How did you resolve it?

**Comment by dinki** [comment]
Sorry @carlos-sarmiento but I can't remember.  I may have done a firmware upgrade on the doorbell.
