### ISSUE TITLE
Issue with AD410

### ISSUE THREAD

**Issue by pstapley** [dchesterton/amcrest2mqtt#78]
I am running the docker on Unraid and I am seeing these errors with an AD410. Let me know if I can provide any further information. Thanks!

an error occurred during closing of asynchronous generator <async_generator object AsyncClient.stream at 0x151197070820>
asyncgen: <async_generator object AsyncClient.stream at 0x151197070820>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/app/amcrest2mqtt.py", line 426, in main
    elif code == "CrossRegionDetection" and payload["data"]["ObjectType"] == "Human":
KeyError: 'ObjectType'

During handling of the above exception, another exception occurred:

RuntimeError: aclose(): asynchronous generator is already running

**Comment by towerhand** [comment]
Same?
https://github.com/dchesterton/amcrest2mqtt/issues/67

**Comment by pstapley** [comment]
Duplicate
